@startuml jweb-notifier
class User {
    ユーザID
    パスワード
    ウォッチリスト
}
note left: ・ユーザIDはメールアドレス\n・パスワードは8文字以上で\n小文字大文字数字の3種含む\n・ウォッチリストはblog複数

class Diary {
    タレントID
    タレント名
    グループ名
}
note left: ・タレントIDはジャニWEBのartist param\n

class Favorite {
    ユーザID
    タレントID
}

interface Notifier {
    Notify()
}

class SlackNotifier {
    ユーザID
    URL
    recipient
    トークン
}

User "0..1" --> "0..n" Favorite
Diary "0..1" --> "0..n" Favorite
User "0..1" --> "0..1" Notifier
Notifier <|-- SlackNotifier
@enduml