name: Branch Build

on:
    push:
        branches:
        - master
        - version-*
jobs:
    branch-build:
        runs-on: golang
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v1
        - name: Build
          run: go build .